config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'dashboard' => 'dashboards#index'

  resources :gadgets, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'location'
      get 'preload'
      get 'preview'
      get 'features'
      get 'requirements'
    end
    resources :reservations, only: [:create, :accept_reservation]
    resources :photos, only: [:create, :destroy]
  end

  get '/your_rents' => 'reservations#your_rents'
  get '/your_reservations' => 'reservations#your_reservations'

  resources :guest_reviews, only: [:create, :destroy]
  resources :owner_reviews, only: [:create, :destroy]

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end

  resources :users, only: [:index, :show]

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  # only dev
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get 'notifications/index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, scope: :recipient_id
  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)

  end

  def target_user(current_user)
    if self.sender_id == current_user.id
      User.find(self.recipient_id)
    elsif self.recipient_id == current_user.id
      User.find(self.sender_id)
    end
  end
end

app/models/gadget.rb
class Gadget < ApplicationRecord
  enum instant: {Request: 0, Instant: 1}
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :guest_reviews

  def cover_photo(size)

    if self.photos.length > 0
      self.photos.first.image
    else
        "blank.jpg"
    end
  end

  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end
end

app/models/guest_review.rb
class GuestReview < Review
  belongs_to :guest, class_name: "User"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  has_many :notifications, dependent: :destroy

  validates_presence_of :body, :conversation_id, :user_id
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :message
end

app/models/owner_review.rb
class OwnerReview < Review
  belongs_to :owner, class_name: "User"
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :gadget
  mount_uploader :image, ImageUploader

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :gadget

  enum status: {Waiting: 0, Approved: 1, Declined: 2}
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  has_many :gadgets
  has_many :reservations
  has_many :guest_reviews, class_name: "GuestReview", foreign_key: "guest_id"
  has_many :owner_reviews, class_name: "OwnerReview", foreign_key: "owner_id"
  mount_uploader :local_image, LocalImageUploader

   def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
     user = User.find_by(email: auth.info.email)

     unless user
       user = User.new(
       name:     auth.extra.raw_info.name,
       provider: auth.provider,
       uid:      auth.uid,
       email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
       sns_image:   auth.info.image,
       password: Devise.friendly_token[0, 20]
       )
       user.skip_confirmation!
       user.save(validate: false)
     end
     user
   end

   def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
     user = User.find_by(provider: auth.provider, uid: auth.uid)

     unless user
       user = User.new(
       name:     auth.info.nickname,
       sns_image: auth.info.image,
       provider: auth.provider,
       uid:      auth.uid,
       email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
       password: Devise.friendly_token[0, 20]
       )
       user.skip_confirmation!
       user.save
     end
     user
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @gadgets = Gadget.where(active: true).limit(6)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @gadgets =@user.gadgets

    # Display all the guest reviews to host (if this user is a host)
    @guest_reviews = Review.where(type: "GuestReview", owner_id: @user.id)

    # Display all the guest reviews to host (if this user is a host)
    @owner_reviews = Review.where(type: "OwnerReview", guest_id: @user.id)
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    if !user.local_image.blank?
      user.local_image
    elsif user.sns_image
      "http://graph.facebook.com/#{user.uid}/picture?type=large"
    #elsif
    #  gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    #  "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
    else
      "person.png"
    end
  end

  def date_japan(time)
    time.strftime("%Y-%m-%d")
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GadgetGo</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <%= stylesheet_link_tag "jquery-ui", :media => "all" %>
    <script src="<%= ENV['GMAP_JS_URL'] %>&libraries=places"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/hot-sneaks/jquery-ui.css">
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <% if user_signed_in? %>
      <script>
        var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>',{
          encrypted: true,
          cluster: 'ap1'
        });

        var channel = pusher.subscribe('user_<%= current_user.id %>_channel');
        channel.bind('notify_message', function(data) {
          alert(data.message);
        });

        channel.bind('notify_unread', function(data) {
          $('#unread_count').html(data.unread_counts);
        });
      </script>
    <% end %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/message' %>
    <div id="wrapper">
      <div class="container">
         <%= yield %>
         <hr />
      </div>
    </div>
    <footer>
        <p>○○○株式会社</p>
        <p>© 2017 Copyright ○○○.</p>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-md-12 banner">
    <h1>新しいテクノロジーを体験しよう！</h1>
  </div>
</div>

<%= form_tag root_path, method: :get do %>
<div class="row">
  <div class="col-md-6">
    <%= text_field_tag :search, params[:search], placeholder: "ガジェット検索", class: "form-control", id: "autolocation" %>
  </div>
  <div class="col-md-3">
    <%= text_field_tag :start_date, params[:start_date], placeholder: "レンタル開始日", class: "form-control datepicker" %>
  </div>
  <div class="col-md-3">
    <%= text_field_tag :end_date, params[:end_date], placeholder: "レンタル終了日", class: "form-control datepicker" %>
  </div>
</div>
<br/><br/>

<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <%= submit_tag "SEARCH", class: "btn btn-normal btn-block" %>
  </div>
</div>
<% end %>
<br/><hr/><br/>

<!-- HOMES -->
<div><h3>新着ガジェット</h3></div>
<br/>

<div class="row">
  <%= render partial: "gadgets/gadgets_list", locals: {gadgets: @gadgets} %>
</div>

<!-- TECHS -->
<div><h3>テクノロジー</h3></div>
<br/>

<div class="row">
  <div class="col-md-4 col-sm-12">
    <a href="#" class="discovery">
      <%= image_tag 'vr.jpg', class: "discovery-card img-rounded center-block" %>
      <div class="middle">VR&AR</div>
    </a>
  </div>
  <div class="col-md-4 col-sm-12">
    <a href="#" class="discovery">
      <%= image_tag 'drone.jpg', class: "discovery-card img-rounded center-block" %>
      <div class="middle">DRONE</div>
    </a>
  </div>
  <div class="col-md-4 col-sm-12">
    <a href="#" class="discovery">
      <%= image_tag 'camera.jpg', class: "discovery-card img-rounded center-block" %>
      <div class="middle">CAMERA</div>
    </a>
  </div>
</div>
<br />
<div class="row">
  <div class="col-md-4 col-sm-12">
    <a href="#" class="discovery">
      <%= image_tag 'smart-watch.jpg', class: "discovery-card img-rounded center-block" %>
      <div class="middle">WATCH</div>
    </a>
  </div>
  <div class="col-md-4 col-sm-12">
    <a href="#" class="discovery">
      <%= image_tag 'game.jpg', class: "discovery-card img-rounded center-block" %>
      <div class="middle">GAME</div>
    </a>
  </div>
  <div class="col-md-4 col-sm-12">
    <a href="#" class="discovery">
      <%= image_tag 'robot.jpg', class: "discovery-card img-rounded center-block" %>
      <div class="middle">ROBOT</div>
    </a>
  </div>
</div>

<!--  -->
<section class="content-section-b">

  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">サービスについて</h2>
        <p class="lead">あなたの家に眠っているガジェットはありませんか？</p>
      </div>
      <div class="col-lg-6">
        <%= image_tag 'no-image.jpg', class: "img-fluid" %>
      </div>
    </div>

  </div>
  <!-- /.container -->
</section>
<section class="content-section-a">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">レンタル</h2>
        <h3 class="section-subheading text-muted">3つのステップで最新ガジェットがあなたの家に届きます</h3>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-search fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">検索</h4>
        <p class="text-muted">まずはあなたの興味のあるガジェットを探して見ましょう。</p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-calendar fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">予約</h4>
        <p class="text-muted">あなたの借りたい日にあわせて予約して見ましょう。</p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-truck fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">受け取り</h4>
        <p class="text-muted">当日朝8時にあなたのお家へ届けます</p>
      </div>
    </div>
  </div>
</section>
<br />

<script>
$('#start_date').datepicker({
  dateFormat: 'dd-mm-yy',
  minDate: 0,
  maxDate: '3m',
  onSelect: function(selected) {
    $('#end_date').datepicker("option", "minDate", selected);
    $('#end_date').attr("disabled", false);
  }
});

$('#end_date').datepicker({
  dateFormat: 'dd-mm-yy',
  minDate: 0,
  maxDate: '3m',

  onSelect: function(selected) {
    $('#start_date').datepicker("option", "maxDate", selected);
  }
});

$(function() {
  $("#autolocation").geocomplete();
})
</script>

app/views/reviews/_guest_form.html.erb
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-normal" data-toggle="modal" data-target="#myModal_<%= reservation.id %>">
  Review Host
</button>

<!-- Modal -->
<div id="myModal_<%= reservation.id %>" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-left">Review Your Host</h4>
      </div>
      <div class="modal-body">
        <%= form_for current_user.guest_reviews.new do |f| %>
          <div class="form-group text-center">
            <div id="stars"></div>
          </div>
          <div class="form-group">
            <%= f.text_area :comment, rows: 3, class: "form-control" %>
          </div>

          <%= f.hidden_field :gadget_id, value: reservation.gadget.id %>
          <%= f.hidden_field :reservation_id, value: reservation.id %>
          <%= f.hidden_field :owner_id, value: reservation.gadget.user.id %>

          <div class="text-center">
            <%= f.submit "Add Review", class: "btn btn-normal" %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>


<script>
  $('#stars').raty({
    path: '/assets',
    scoreName: 'guest_review[star]',
    score: 1
  });
</script>

app/views/reviews/_guest_list.html.erb
<% if @guest_reviews.count == 0 %>
  <div class="text-center">
    <h4>There are no reviews.</h4>
  </div>
<% else %>
  <% @guest_reviews.order(id: :desc).each do |r| %>
    <hr/>
    <div class="row">
      <div class="col-md-3 text-center">
        <%= image_tag avatar_url(r.guest), class: "img-circle avatar-medium" %><br/><br/>
        <strong><%= r.guest.name %></strong>
      </div>
      <div class="col-md-9">
        <div id="star_<%= r.id %>"></div>
        <% if current_user && current_user == r.guest %>
          <span class="pull-right">
            <%= link_to r, method: :delete, data: {confirm: "Are you sure?"} do %>
              <i class="fa fa-trash-o fa-lg"></i>
            <% end %>
          </span>
        <% end %>
        <div><%= date_japan(r.created_at) %></div>
        <div><%= r.comment %></div>
      </div>
    </div>
    <script>
      $('#star_<%= r.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= r.star %>
      });
    </script>
  <% end %>
<% end %>

app/views/reviews/_owner_form.html.erb
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-normal" data-toggle="modal" data-target="#myModal">
  Review Guest
</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-left">Review Your Host</h4>
      </div>
      <div class="modal-body">
        <%= form_for current_user.owner_reviews.new do |f| %>
          <div class="form-group text-center">
            <div id="stars"></div>
          </div>
          <div class="form-group">
            <%= f.text_area :comment, rows: 3, class: "form-control" %>
          </div>

          <%= f.hidden_field :gadget_id, value: reservation.gadget.id %>
          <%= f.hidden_field :reservation_id, value: reservation.id %>
          <%= f.hidden_field :guest_id, value: reservation.user.id %>

          <div class="text-center">
            <%= f.submit "Add Review", class: "btn btn-normal" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script>
  $('#stars').raty({
    path: '/assets',
    scoreName: 'guest_review[star]',
    score: 1
  });
</script>

app/views/reviews/_owner_list.html.erb
<% if @owner_reviews.count == 0 %>
  <div class="text-center">
    <h4>There are no reviews.</h4>
  </div>
<% else %>
  <% @owner_reviews.order(id: :desc).each do |r| %>
    <hr/>
    <div class="row">
      <div class="col-md-3 text-center">
        <%= image_tag avatar_url(r.owner), class: "img-circle avatar-medium" %><br/><br/>
        <strong><%= r.owner.name %></strong>
      </div>
      <div class="col-md-9">
        <div id="star_<%= r.id %>"></div>
        <% if current_user && current_user == r.owner %>
          <span class="pull-right">
            <%= link_to r, method: :delete, data: {confirm: "Are you sure?"} do %>
              <i class="fa fa-trash-o fa-lg"></i>
            <% end %>
          </span>
        <% end %>
        <div><%= date_japan(r.created_at) %></div>
        <div><%= r.comment %></div>
      </div>
    </div>
    <script>
      $('#star_<%= r.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= r.star %>
      });
    </script>
  <% end %>
<% end %>

app/views/shared/_devise_message.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top" style="margin-bottom: 0px">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Gadget Go", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <%= form_tag root_path, class: "navbar-form navbar-left", method: :get do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "検索", class: "form-control" %>
        </div>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <button class="btn btn-form btn-small">
            <%= link_to "Gadget提供", new_gadget_path, style: "color: white; text-decoration: none;" %>
          </button>
        </li>

        <% if !user_signed_in? %>
          <li><%= link_to "ログイン", new_user_session_path, class: "navbar-link" %></li>
          <li><%= link_to "ユーザー登録", new_user_registration_path, class: "navbar-link"%></li>
        <% else %>
          <li>
            <%= link_to notifications_index_path, class: "navbar-brand" do %>
              <i class="fa fa-bell fa-lg icon-babu bell-position"></i>
              <span class="badge" id="unread_count"><%= @notifications_count if @notifications_count > 0 %></span>
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
              role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
              <%= current_user.name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Dashboard", dashboard_path %></li>
              <li><%= link_to "あなたのガジェット", gadgets_path %></li>
              <li><%= link_to "予約リクエスト", your_reservations_path %></li>
              <li><%= link_to "レンタルリスト", your_rents_path %></li>
                <li role="separator" class="divider"></li>
              <li><%= link_to "プロフィール変更", edit_user_registration_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<% if (user_signed_in?) && !current_page?(root_path) %>
  <nav class="navbar navbar-default" style="background-color: #CACCCD">
    <div class="container">
      <ul class="nav navbar-nav">
        <li <% if current_page?(dashboard_path) %> class="active" <% end %> ><%= link_to "ダッシュボード", dashboard_path %></li>
        <li <% if current_page?(gadgets_path) %> class="active" <% end %> ><%= link_to "あなたのガジェット", gadgets_path %></li>
        <li <% if current_page?(conversations_path) %> class="active" <% end %> ><%= link_to "メッセージ", conversations_path %></li>
      </ul>
    </div>
  </nav>
<% end %>